### PR TITLE
Update sigit.py

### PR DESCRIPTION
**Pull request by Somraj2929**
from googlesearch import search gaves error in python3 so instead of this use ...***from googlesearch.googlesearch import GoogleSearch***
Look at code.

### CODE REVIEW

**Comment by Somraj2929** [comment]
For Python3 google search api changed. have a look....

**Review by Jdoxka0 — APPROVED** [review]

**Review by Jdoxka0 — APPROVED** [review]

**Comment by Jdoxka0** [comment]
💪

**Comment by Jdoxka0** [comment]
Dope

**Review by Jdoxka0 — APPROVED** [review]
Dope

**Comment by Jdoxka0** [comment]
Fixed

**Pull request merged**
